### ISSUE TITLE
Publish changes to npm?

### ISSUE THREAD

**Issue by max-b** [sudomesh/ipk-builder#1]
Hey @Juul  - I dunno how often were gonna actually need this fix, but there do tend to be bunch of folks who show up to our meetings with macs and strange file paths. Plus it's an easy fix. Here's the original issue:
https://github.com/sudomesh/makenode/issues/11

I think all you need to do is publish to npm and then maybe we have to adjust the package.json file in makenode?

**Comment by paidforby** [comment]
was actually published to npm
https://www.npmjs.com/package/ipk-builder
